### ISSUE TITLE
Server crash when starting up

### ISSUE THREAD

**Issue by seasquirt** [b3spectacled/modernbetaforge#7]
When starting a server on the latest versions (1.1.0.0 and up), a duplicate mod error is thrown. Any version below 1.1.0.0 works fine.
[crash-2024-11-12_22.02.43-server.txt](https://github.com/user-attachments/files/17725549/crash-2024-11-12_22.02.43-server.txt)

**Comment by b3spectacled** [comment]
Hi, since it only affects versions 1.1.0.0, I investigated this under the notion that it might be a mixin-related issue.

I think this is related to this old mixin issue: https://github.com/SpongePowered/Mixin/issues/253

There is a development jar that implements a workaround for this problem. You can find it in the 'build-artifacts' download on this page: https://github.com/b3spectacled/modernbetaforge/actions/runs/11811063170

Could you please test it and report back? Thank you.

**Comment by seasquirt** [comment]
looks like that worked

**Comment by b3spectacled** [comment]
Awesome, I'll be pushing out this fix for 1.12.2-1.2.2.3. Feel free to keep using the development jar or download the new update when it's posted; they'll be the same jar. Thanks again!
