### ISSUE TITLE
[Feature Request] Void Borders/Barrier Chunk Options

### ISSUE THREAD

**Issue by Handeril** [b3spectacled/modernbetaforge#9]
I explored an Indev World that was limited to 512x512 and noticed that at the edge of the map, it's a repeating Flat World that uses normal Overworld features. [My modpack generates Superflat Worlds differently.] The best way I can describe it, it is as if server admins were doing some sort of survival challenge and they were staging stuff outside the map to WorldEdit into the play area later.

I am curious if it would be possible to either make chunks beyond the map dimensions border chunks of Air Blocks, or even Barrier Blocks?
Maybe have it be an experimental option? [If it works, maybe it could become a preset like "Indev Bordered".]

Thank you for your time, in advance!

**Comment by b3spectacled** [comment]
Is there any reason why the `worldBorder` game option couldn't be used in this case?

**Comment by Handeril** [comment]
It could be used, but is there a way it could be added to the options while creating a world?
[Could also be added to the presets.]

**Comment by b3spectacled** [comment]
I was thinking about implementing your suggestion, then I realized that the world border can only be square-shaped and thus would not work with odd-shaped levels where the width and length is not equal. So I'm probably not going to do this, for now.

FWIW, I did consider barrier blocks, a long time ago, but the issue there is that barrier blocks can only extend up to the world height limit (players could go over it) and cannot be waterlogged for Island levels (players can go under it by going underwater). So that didn't seem workable to me either.

EDIT: Another factor I considered was making sure that Indev worlds could be 'finished', from start to The End, so I also wanted players to be able to travel as far as they want in the Nether and still have them return to a valid spot in the Overworld, even if they ended up in the middle of nowhere.
